import TestModule, ToolsRuntime;

macro TestFunc(v)

    /*var err = ErrorsModel();
    err.appendError("Пример предупреждения", err.TypeWarning);
    err.appendError("Пример ошибки", err.TypeError);
    err.appendError("Пример сообщения", err.TypeInfo);

    var dlg = ErrorDlg(ErrorModeInformation);
    dlg.setMessage("Описание назначения окна:");
    dlg.setErrors(err);
    var result = dlg.exec();*/
    var obj = TestObject();
        debugbreak;
    var prm = obj.testVariant(12);

    println(prm);
end;